[build-system]
requires = ["zigcc-build"]
build-backend = "zigcc_build"

[project]
name = "demo-package"
version = "1.0.0"
description = "A demo package built with zigcc"

[tool.zigcc-build]
module-name = "demo"
sources = ["src/hello.c"]
defines = ["HELLO_MACRO"]
configurer-script = "configure.py"
